### PR TITLE
VOL-278: Enable Customizing the UF Page Title.

### PR DESCRIPTION
**Pull request by agileware**
Use page title for Angular pages that matches the pattern that crmUi matches.
Add page title replacement for (user-facing) opportunities search page.

---

 * [VOL-278: Enable Customizing the UF Page Title](https://issues.civicrm.org/jira/browse/VOL-278)

### CODE REVIEW

**Comment by GinkgoFJG** [comment]
Looks like this needs some more work. Now every page in the volunteer Angular app gets the title "Search for Volunteer Opportunities." Also, why did you make the change to the XML file? It seems superfluous.

**Comment by agileware** [comment]
@GinkgoFJG the change to the XML file is needed for crmUi's crmPageTitle directive to work - it looks for the known page title (which has been hardcoded in crmUi to start out as 'CiviCRM') and will *only* replace that.

In our testing this only sets the title to "Search for Volunteer Opportunities" for the /volunteer/opportunities route -- will need to re-test the event pages but other parts of the angular app should say "CiviCRM"

**Comment by GinkgoFJG** [comment]
A read of the directive code suggests that's not quite accurate. It [starts off](https://github.com/civicrm/civicrm-core/blob/master/ang/crmUi.js#L5) with the assumption that the page title is "CiviCRM," but later that page title is set to -- well, whatever [you set it to](https://github.com/civicrm/civicrm-core/blob/master/ang/crmUi.js#L5).

I ran into the problem by loading up the search vol opps screen then loading up the manage project screen. I suspect the problem can be resolved by using the directive on each route (i.e., explicitly setting page titles everywhere).

**Comment by jusfreeman** [comment]
@GinkgoFJG feel free to close this PR or pick it up and run with it. Agileware are no longer supporting any organisations using CiviVolunteer.

**Pull request closed without merging**
