### PR TITLE
Regenerate Civix Generated files

### PR DESCRIPTION
**Pull request by seamuslee001**
ping @eileenmcnaughton @colemanw

### CODE REVIEW

**Comment by seamuslee001** [comment]
ping @MikeyMJCO as well

**Comment by eileenmcnaughton** [comment]
@MikeyMJCO @ginkgomzd I feel like I tried to broker a co-maintainer relationship here but I think I failed at the post - can I propose again that @MikeyMJCO is added as co-maintainer & we tag a release on this?

**Comment by ginkgomzd** [comment]
Mikey and I agreed to work on maintaining the extension and left off seeing who would have time to test first.

Let's focus on the issue at hand, I have little care for who has tagging rights on the repo.

I think if there is anyone, not requesting, but vouching for a release, then it should be tagged as such.

**Comment by eileenmcnaughton** [comment]
I'm pretty sure I can vouch for the master branch being more reliable that the current release based on all the things that have changed in master to adapt to civi changes that are not released

We should probably decide whether a release is going to happen in x period of time & if not consider removing this from buildkit / demo sites

**Comment by ginkgomzd** [comment]
Okay, as long as we are vouching based on commits...

I reviewed the two release candidates and remembered that one was a conservative release and the other is known to have bugs.

Master already superseded the conservative release and those commits have more assurance than most.

I pushed the tag for v2.4.0.

**Comment by eileenmcnaughton** [comment]
thanks @ginkgomzd that's a relief since I've spent a bit of time telling people to download from github rather than use the tagged release

**Pull request merged**
