### PR TITLE
VOL-287: Replace opportunities settings stub with API call

### PR DESCRIPTION
**Pull request by agileware**
https://issues.civicrm.org/jira/browse/VOL-287

### CODE REVIEW

**Comment by ginkgomzd** [comment]
Looks good to me

**Comment by agileware** [comment]
Should've tested better as non admin - of course you can't query the settings API from javascript unless you have "administer civicrm".

**Comment by GinkgoFJG** [comment]
@agileware, thanks for fleshing out this feature by adding actual settings.

We already have a hack in place for addressing the problem of the permissions needed for the various calls involved in building an Angular page. We aren't proud of it, but one hack pattern is clearly preferable to a new pattern each time there's a new problem to solve.

The `supporting_data` resolve property makes a call to `api.VolunteerUtil.supporting_data`. This is where we've stashed other junk needed to render a page. For the controller in question, you'll see the roles are fetched this way. The pattern is consistent across other Angular-based CiviVolunteer pages.

Could you please re-work your logic to fit within the established pattern?

Thanks!

**Comment by jusfreeman** [comment]
@GinkgoFJG feel free to close this PR or pick it up and run with it. We are no longer supporting any organisations using CiviVolunteer.

**Pull request closed without merging**
