### PR TITLE
use civicrm email functionality to keep track of the interactions

### PR DESCRIPTION
**Pull request by yashodha**
Before
----------
No tracking of email sent.

After
-------
Since email has been sent via CiviCRM, Email activity is logged.

### CODE REVIEW

**Comment by yashodha** [comment]
@ginkgomzd Thoughts?

**Comment by ginkgomzd** [comment]
potentially good, but please ask me in a week.

**Comment by yashodha** [comment]
@ginkgomzd ready to merge?

**Comment by yashodha** [comment]
@ginkgomzd Let me know if this can be merged. Thanks!

**Comment by yashodha** [comment]
@ginkgomzd This is definitely an improvement.
Let me know if this can be merged. Thanks!

**Comment by nasiralamreeki** [comment]
@ginkgomzd will this be approved? Also can we depend on this extension getting continued support it seems it's getting stale since 2021.

**Comment by ginkgomzd** [comment]
Okay, I've merged this. I think it may break some people's usage but I'm really not sure which scenario is more prevalent.

**Comment by ginkgomzd** [comment]
@nasiralamreeki  RE maintenance of the extension. I've stated that I would facilitate transition to a new maintainer if anyone expressed interest, but there have been no volunteers. I've asked the community for contributions in the form of testing release-candidates and have received zero testing feedback. I'm not sure how much demand there is for this extension anymore. There are other ways to accomplish the same things in CiviCRM. The only unique functionality I think is the scheduling tool. I think were I to get a chunk of funding, I would try to extract and generalize the scheduling tool. I have a better opportunity search and directory, but it is not generalized enough for public release and have not found interest in funding completion of the release of that. I would be happy to discuss any of these if you think the extension is important enough to your organization to fund some maintenance. 
Cheers!

**Comment by yashodha** [comment]
@ginkgomzd thanks for merging!

**Pull request merged**
