### PR TITLE
VOL-288: Fixed install bug: CiviCRM_API3_Exception: "N is not a valid…

### PR DESCRIPTION
**Pull request by GinkgoFJG**
… option for field option_group_id"

### CODE REVIEW

**Comment by GinkgoFJG** [comment]
Hey, @totten. This works, but it feels wrong. Is there a better way to do this? TLDR from the ticket:

If you're programmatically creating an optionGroup and adding an optionValue to it, you have to clear caches between steps 1 and 2 or you'll get the error above.

**Comment by totten** [comment]
Yeah, it feels excessive to do a full rebuild. Assuming the problem is as-described, it would be more proportionate to say, e.g., "whenever you add/edit/delete an OptionGroup or OptionValue, flush the related caches".

The challenge would be figuring out where those caches are. I don't know this specific bug, but on general grounds these places might be implicated:
 * `CRM_Core_OptionGroup` (has some unintuitive double-caching)
 * `CRM_Core_PseudoConstant` (has caching and has been an issue in the past; would expect it to have been beaten into shape by now, but you never know)
 * `CRM_Core_BAO_OptionGroup` (sounds plausible but don't see any caching logic)
 * `CRM_Core_BAO_OptionValue` (eg has some caching in `getOptionValuesArray`)

You might try doing a few smaller/more targeted flushes (e.g. `CRM_Core_Config::singleton()->cleanupCaches()`)

**Comment by ginkgomzd** [comment]
@GinkgoFJG @totten I propose we merge this. Excessive cache clearing on enabling the extension seems like a minor sin and no one is jumping for the opportunity to make it more selective.
Thoughts?

**Comment by totten** [comment]
@ginkgomzd - Yes, IMHO, it's better for the extension to fire `rebuildMenuAndCaches()` than to let an installer bug sit around. I wouldn't recommend it as a default/pro-forma practice for all extensions, but it's a valid work-around if it's needed.

Aside: [this issue in mosaicomsgtpl](https://github.com/civicrm/org.civicrm.mosaicomsgtpl/issues/3) is another example of firing `rebuildMenuAndCaches()`.  It's not necessary to read/understand for resolving this one, but it could give some additional perspective.

**Pull request merged**
