### PR TITLE
Fix docs links

### PR DESCRIPTION
**Pull request by homotechsual**

### CODE REVIEW

**Comment by homotechsual** [comment]
@ginkgomzd the book currently can't be built/rebuilt until this is merged. As a result unfortunately it might disappear from `docs.civicrm.org` due to changes to `docs-publisher`

**Comment by ginkgomzd** [comment]
Thanks @homotechsual 

I assume you are building off the master branch?

What is going on with docs-publisher? Looks like just 3 months ago I had to update the links to a different scheme. Can we hope this scheme will stick?

**Comment by homotechsual** [comment]
This scheme has been stuck for a while now - there was a change to the mkdocs.uni files - this is a content change - mostly because of improved broken link detection only affected Volunteer because the links were to URLs `../thing/` and not pages `./thing.md` no further changes this will always work as it's just Markdown links now :-)

**Comment by homotechsual** [comment]
Still can't build Michael,

```
  Build errors encountered. Book 'volunteer' in language 'English' was not published. There was a build error: 'MkDocs was unable to build the book. MkDocs command output: INFO     -
  Cleaning site directory
  INFO     -  Building documentation to directory: /var/www/civicrm-docs/var/cache/dev/publishing/publish_volunteer_en_1644420793
  WARNING  -  Documentation file 'sign-up-form.md' contains a link to 'assignment.md' which is not found in the documentation files.
 ```

**Comment by ginkgomzd** [comment]
added the missing 's'

**Comment by homotechsual** [comment]
https://docs.civicrm.org/volunteer/en/latest/

**Pull request merged**
